import { Mail, MapPin, Phone } from "lucide-react";
import { type Photo } from "react-photo-album";
import weddingEventsImg from "../../public/images/sala-bankietowa-vita-1.jpg";
import baptismEventsImg from "../../public/images/sala-bankietowa-vita-2.jpg";
import businessEventsImg from "../../public/images/sala-bankietowa-vita-4.jpg";
import occasionalEventsImg from "../../public/images/sala-bankietowa-vita-6.jpg";

import { type TNavItem, type TContactItem, type TOfferItem, type TDishes } from "@/types";

export const NAV_ITEMS: TNavItem[] = [
	{ href: "/", label: "Strona główna" },
	{ href: "/oferta", label: "Oferta" },
	{ href: "/galeria", label: "Galeria" },
	{ href: "/propozycja-menu", label: "Propozycja menu" },
	{ href: "/kontakt", label: "Kontakt" },
];

export const OFFER_ITEMS: TOfferItem[] = [
	{
		id: "weddings",
		title: "Wesela",
		shortDescription: "Organizujemy wesela na miarę marzeń.",
		description:
			"Naszą specjalnością są wesela. Oferujemy kompleksową organizację przyjęć weselnych. Nasi kucharze przygotują pyszne, tradycyjne dania, a nasz zespół zadba o oprawę muzyczną i dekoracje, aby Państwa wesele było wyjątkowe. Standardowy pakiet weselny obejmuje przystawkę, zupę, danie główne, deser oraz napoje, ale istnieje również możliwość skomponowania własnego, indywidualnego menu.",
		image: weddingEventsImg,
	},
	{
		id: "baptisms",
		title: "Komunie i chrzciny",
		shortDescription: "Przyjęcia komunijne oraz chrzciny w eleganckiej atmosferze.",
		description:
			"Organizujemy przyjęcia komunijne i chrzciny. Nasza sala bankietowa to idealne miejsce na organizację takich wydarzeń. Chętnie dostosujemy się do Państwa preferencji i pomożemy w zorganizowaniu wymarzonego wydarzenia.",
		image: baptismEventsImg,
	},
	{
		id: "corporate-events",
		title: "Imprezy firmowe",
		shortDescription: "Konferencje, szkolenia i inne imprezy firmowe.",
		description:
			"Nasza sala bankietowa to idealne miejsce na organizację konferencji, szkoleń, bankietów i innych wydarzeń firmowych. Dysponujemy nowoczesnym zapleczem technicznym, a nasz zespół zadba o sprawną organizację i profesjonalną obsługę Państwa gości. Zapraszamy do zapoznania się z pełną ofertą na naszej stronie internetowej. Chętnie dostosujemy się do Państwa preferencji i pomożemy w zorganizowaniu wymarzonego wydarzenia.",
		image: businessEventsImg,
	},
	{
		id: "occasional-events",
		title: "Imprezy okolicznościowe",
		shortDescription: "Przyjęcia urodzinowe, jubileuszowe i inne.",
		description: `Organizujemy również urodziny, inne imprezy rodzinne. Zadbamy o to, aby Państwa wydarzenie było pełne radości i pamiętane przez długi czas. Nasi kucharze przygotują pyszne dania, a nasz zespół zadba o oprawę muzyczną i dekoracje.`,
		image: occasionalEventsImg,
	},
];

export const CONTACT_ITEMS: TContactItem[] = [
	{
		icon: <Mail size={22} strokeWidth={2} />,
		title: "E-mail",
		content: "kontakt@sala-vita.pl",
		href: "mailto:kontakt@sala-vita.pl",
	},
	{
		icon: <Phone size={22} strokeWidth={2} />,
		title: "Telefon",
		content: "+48 503 053 294",
		href: "tel:+48503053294",
	},
	{
		icon: <MapPin size={22} strokeWidth={2} />,
		title: "Adres",
		content: "ul. Gminna 4, 42-261 Starcza",
		href: "https://maps.app.goo.gl/hTUJYDz5p9s7WVAn9",
	},
];

export const GALLERY_IMAGES: Photo[] = [
	{
		src: "/images/sala-bankietowa-vita-1.jpg",
		width: 2000,
		height: 2000,
		alt: "1",
	},
	{
		src: "/images/sala-bankietowa-vita-2.jpg",
		width: 2000,
		height: 2000,
		alt: "2",
	},
	{
		src: "/images/sala-bankietowa-vita-3.jpg",
		width: 2000,
		height: 2000,
		alt: "3",
	},
	{
		src: "/images/sala-bankietowa-vita-4.jpg",
		width: 2000,
		height: 2000,
		alt: "4",
	},
	{
		src: "/images/sala-bankietowa-vita-5.jpg",
		width: 2000,
		height: 2000,
		alt: "5",
	},
	{
		src: "/images/sala-bankietowa-vita-6.jpg",
		width: 2000,
		height: 2000,
		alt: "6",
	},
	{
		src: "/images/sala-bankietowa-vita-7.jpg",
		width: 2000,
		height: 2000,
		alt: "7",
	},
	{
		src: "/images/sala-bankietowa-vita-8.jpg",
		width: 2000,
		height: 2000,
		alt: "8",
	},
	{
		src: "/images/sala-bankietowa-vita-9.jpg",
		width: 2000,
		height: 2000,
		alt: "9",
	},
	{
		src: "/images/sala-bankietowa-vita-10.jpg",
		width: 2000,
		height: 2000,
		alt: "10",
	},
	{
		src: "/images/sala-bankietowa-vita-11.jpg",
		width: 2000,
		height: 2000,
		alt: "11",
	},
	{
		src: "/images/sala-bankietowa-vita-12.jpg",
		width: 2000,
		height: 2000,
		alt: "12",
	},
];

export const DISHES: TDishes[] = [
	{
		title: "Obiady",
		meals: [
			"Rosół z makaronem lub zupa-krem (z pieczarek, białych warzyw, zielonych warzyw, pomidorów lub pora) z groszkiem ptysiowym lub grzankami",
			"Rolada wołowa w sosie",
			"Polędwiczki wieprzowe w sosie śliwkowym",
			"Polędwiczki wieprzowe w sosie śmietanowym z zielonym pieprzem",
			"Polędwiczki wieprzowe w sosie grzybowym",
			"Rolada wieprzowa w sosie",
			"Schab w sosie borowikowym",
			"Żeberka barbecue",
			"Żeberka musztardowo-miodowe",
			"Kotlet schabowy panierowany",
			"Kotlet schabowy w panko i sezamie",
			"Kotlet schabowy z kością marynowany w mleku, czosnku i cebuli",
			"Kotlet cordon bleu z szynką i serem",
			"Kieszonki schabowe panierowane nadziewany boczkiem, porem i serem",
			"Karczek z grilla z cebulą",
			"Pieczeń wieprzowa w sosie",
			"Sakiewki ze schabu z pieczarkiami i serem",
			"Udko z kaczki z jabłkami i pomarańczą z goździkiem i cynamonem",
			"Filet z kurczaka po parysku z dodatkiem chili i ziół prowansalskich",
			"Filet z kurczaka z pieczarkami i serem",
			"Filet z kurczaka panierowany",
			"Sakiewki z kurczakiem w cieście francuskim z pieczarkami, serem i brokułem",
			"Filet z kurczaka zapiekany z mozzarellą i suszonymi pomidorami",
			"De volaille z masłem i serem",
			"Rolada z indyka z warzywami",
			"Rolada z indyka z suszonymi pomidorami w szynce szwarcwaldzkiej",
			"Eskalopki z kurczaka sosie śmietanowo-ziołowo-serowym",
			"Grillowany filet z kurczaka z ananasem, serem i żurawiną",
			"Udko z rożna z czosnkiem i rozmarynem",
			"Łosoś w sosie koperkowo-cytrynowym",
			"Dorsz w cieście piwnym",
			"Surówka z czerwonej kapusty z jabłkiem i cebulą",
			"Surówka z czerwonej kapusty z majonezem",
			"Buraczki z żurawiną",
			"Buraczki z cebulką",
			"Buraczki z chrzanem",
			"Surówka z czerwonej kapusty z żurawiną i prażonymi migdałami",
			"Surówka z białej kapusty z jarmużem, gruszką i orzechami",
			"Surówka z kapusty pekińskiej",
			"Colesław",
			"Surówka z kapusty pekińskiej w sosie tzatziki",
			"Surówka z kiszonej kapusty",
			"Surówka z marchewki z pomarańczą lub ananasem",
			"Surówka z marchewki i pora z dodatkiem majonezu",
			"Surówka z selera z rodzynkami lub mizeria",
			"Surówka z marchewki i selera",
			"Kapusta zasmażana z białej kapusty lub z kiszonej",
			"Ziemniaki w ziołach",
			"Ziemniaki gotowane z koperkiem",
			"Kluski śląskie",
			`Kluski "żelazne"`,
			"Ryż rozmaitości",
			"Kasza bulgur z suszonymi pomidorami i natką pietruszki",
			"Gratiny ziemniaczane pieczone",
		],
	},
	{
		title: "Kolacje",
		meals: [
			"Barszczyk z krokietem lub pasztecikiem z mięsem",
			"Żurek z jajkiem i kiełbasą",
			"Bogracz wieprzowy",
			"Zupa gulaszowa",
			"Strogonow",
			"Kociołek myśliwego (wołowina, boczek, kiełbasa, fasola czerwona, grzyby)",
			"Kwaśnica na żeberku z boczkiem i kiełbasą",
			"Pieczeń wieprzowa z kwaśną kapustą zasmażaną",
		],
	},
	{
		title: "Zimne dania",
		meals: [
			"Sałatka jarzynowa",
			"Sałatka królewska",
			"Sałatka makaronowa z szynką",
			"Sałatka pieczarkowa",
			"Sałatka z tuńczykiem",
			"Sałatka meksykańska",
			"Sałatka z wędzonym kurczakiem i ryżem",
			"Sałatka cezar",
			"Sałatka z kurczakiem, ananasem, kiełkami fasoli mung, porem i kukurydzą",
			"Sałatka brokułowa z pomidorem i jajkiem",
			"Sałatka brokułowa z kurczakiem i fetą z sosem czosnkowym",
			"Sałatka z pieczonego buraka z fetą i granatem na rukoli + sos balsamiczny",
			"Sałatka nicejska",
			"Sałatka grecka",
			"Sałatka gyros",
			"Mix sałat z gruszką, warzywami i grillow. kurczakiem+parmezan",
			"Półmiski mięs pieczonych (schab, karczek, filety nadziewane, pasztet)",
			"Deski serów z orzechami, oliwkami i winogronem",
			"Koreczki caprese",
			"Carpaccio z gruszki na sałacie z winogronem, orzechami, parmezanem i szynką parmeńską+ sos balsamiczny",
			"Melon w szynce parmeńskiej",
			"Galaretki wieprzowe",
			"Jajko z chrzanem w szynce i galarecie",
			"Schab po warszawsku",
			"Kurczak z pieczarkami i serem w cieście francuskim",
			"Śledzie w oleju, śmietanie lub po kaszubsku",
			"Rolaki szpinakowe z wędzonym łososiem",
			"Tortille – różne rodzaje",
			"Tarta z boczkiem i porem",
			"Tarta z chorizo i karmelizowaną czerwoną cebulką",
			"Tarta z brokułem, papryką i porem",
			"Tartinki – różne rodzaje",
			"Paszteciki kruche z mięsem lub kapustą i grzybami",
			"Mini burgerki wołowe",
			"Vol-au-vent z serkiem śmietankowym, szczypiorkiem i wędzonym łososiem",
			"Grissini z rukolą i szynką parmeńską",
			"Tatar wołowy",
			"Koszyczki z ciasta francuskiego z serem camembert, orzechami i gruszką",
			"Faszerowany pomidory – różne rodzaje",
			"Przysmaki z wiejskiego stołu (szynka, baleron, salceson, kiełbasa, smalec...)",
			"Faszerowane sakiewki z ciasta francuskiego – różne nadzienia",
		],
	},
];

export const PROPOSAL_MENU: TDishes[] = [
	{
		title: "Obiad",
		meals: [
			"Rosół z makaronem",
			"De volaille",
			"Rolada wieprzowa z sosem",
			"Kotlet schabowy po parysku",
			"Kluski śląskie",
			"Ziemniaki gotowane z koperkiem",
			"Kapusta zasmażana",
			"Surówka z czerwonej kapusty",
			"Colesław",
		],
	},
	{
		title: "Deser",
		meals: ["Stół słodkości i owoców", "Kawa i herbata bez limitu"],
	},
	{
		title: "Przekąski zimne",
		meals: [
			"Półmiski mięs pieczonych (schab, karczek, boczek, pasztet)",
			"Śledzik w oleju z cebulą",
			"Deski serów z oliwkami, winogronem i orzechami",
			"Sałatka gyros",
			"Sałatka makaronowa z brokułem, kurczakiem i warzywami",
			"Sałatka grecka",
			"Galaretki wieprzowe",
			"Kurczak w cieście francuskim",
		],
	},
	{
		title: "Kolacja do wyboru",
		meals: [
			"Barszczyk z krokietem",
			"Bogracz",
			"Kociołek myśliwego",
			"Flaczki wołowe",
			"Zupa gulaszowa",
		],
	},
];
